# These are supported funding model platforms
github: personizeai
# ko_fi: # Replace with a single Ko-fi username
# open_collective: # Replace with a single Open Collective username
# custom: ['https://your-custom-link.com']
